Repository strsryw/belajargit, pull requests merged in 2025-05, with the labels that each got.

#15 close #14
  config/config.php
Labels: enhancement

#17 close #13
  views/dashboard.html
Labels: enhancement

#20 laporan outlet mkt5
  views/laporanoutletmkt5.html
Labels: enhancement

#21 close #19
  views/laporanvisitrekap.html
Labels: enhancement

#23 close #22
  views/laporanvisitrekap.html
Labels: bug, enhancement

#25 close #24
  views/about.html
Labels: enhancement

#28 close #26
  views/laporanoutletmkt5.html
Labels: enhancement

#29 close #27
  views/laporanvisitrekap.html
Labels: enhancement

#32 close #30
  views/test.html
Labels: enhancement

#33 close #31
  views/test2.html
Labels: enhancement

#36 closes#34
  views/test3.html
Labels: enhancement

#37 close#35
  views/test4.html
Labels: enhancement

#39 closes #38
  views/test5.html
Labels: enhancement

#41 tambah catatan
  views/catatan.html
Labels: documentation

#44 resolve bentrok
  views/catatan.html
Labels: documentation

#46 tes
  views/tes.html
Labels: enhancement
